name: TimeTracker
main: de.dustplanet.timetracker.TimeTracker
version: ${project.version}-b${BUILD_NUMBER}
author: xGhOsTkiLLeRx
commands:
  tracker:
    description: Tracks the time
    usage: /tracker help|hilfe|h